// 365 quotes, one per day-of-year. Rotated deterministically.
export const QUOTES_365 = [
  "Ship the ugly draft before noon.",
  "Volume fixes what taste can't yet see.",
  "The algorithm rewards consistency, not genius.",
  "You don't need motivation, you need a calendar.",
  "Post it. Delete it tomorrow if you must.",
  "Every skipped day is a gift to your competition.",
  "Дисциплина скучная. Свобода нет.",
  "Employees trade hours. You trade assets.",
  "Your phone is not your friend before 10am.",
  "The first 100 videos are tuition, not content.",
  "Stop editing. Start publishing.",
  "Money isn't the goal, it's the exit ticket.",
  "Don't polish garbage, ship the next thing.",
  "Talent without reps is just potential gossip.",
  "No one's watching you fail, so fail faster.",
  "Доказывать нужно себе. Остальные подождут.",
  "Retention is earned in the first 3 seconds.",
  "You're not tired, you're unfocused.",
  "Sleep is a performance drug. Take it.",
  "The grind has no highlight reel.",
  "Optimization is procrastination in a suit.",
  "Today's avoidance is tomorrow's panic.",
  "Your excuses are getting really creative, huh.",
  "One bad video won't kill you. Silence will.",
  "The editor you hire pays for himself in hours saved.",
  "You can't out-hustle a broken routine.",
  "Каждый 'завтра' крадёт час у будущего тебя.",
  "Delete the app, not the habit.",
  "If it's free, your attention is the bill.",
  "Boredom is the tax on originality.",
  "Stop asking for permission you already have.",
  "Dopamine loans have brutal interest rates.",
  "The boss inside you gets paid first.",
  "Watch time beats watch count.",
  "You already know what to do. Do it.",
  "Discipline equals freedom in 18 months.",
  "Your first draft is supposed to be bad.",
  "The only audience that matters today is your camera.",
  "Systems don't care about your mood.",
  "If it scares you and helps you, do it first.",
  "Ленивый мозг умеет оправдываться лучше, чем работать.",
  "CTR lies. Watch time tells the truth.",
  "Don't film more, film better hooks.",
  "Freedom costs an unreasonable amount of focus.",
  "No editor, no problem. Cut it yourself at 2am.",
  "Your competition is scrolling right now. Good.",
  "Write the title before the script.",
  "If you can't explain it in 8 seconds, cut it.",
  "The camera never hated you. That's projection.",
  "Output builds confidence. Thinking does not.",
  "Your future self is watching this moment.",
  "Bipolar stable is a stack, not a vibe.",
  "Pills on time. Lights out on time. Repeat.",
  "ADHD isn't an excuse, it's a design constraint.",
  "Build the rails, ride the train.",
  "Routine is the cheat code you keep refusing.",
  "Каждое утро решаешь: винишь систему или строишь её.",
  "The gym is non-negotiable. Non-negotiable.",
  "You don't rise to motivation. You fall to habits.",
  "Stop waiting for the perfect idea to arrive.",
  "Your 10th video will be better than your 1st.",
  "Your 100th will be unrecognizable.",
  "Publish first, perfect never.",
  "Everyone's first hundred were garbage, including theirs.",
  "Comparison is a slow leak on a long road.",
  "The thumbnail is the video. Respect it.",
  "Don't chase views. Chase the one right viewer.",
  "Watch your own content twice. Then cut 30%.",
  "If you're bored making it, they're bored watching it.",
  "Хватит строить планы. Пора строить привычки.",
  "The script is a scalpel, not a novel.",
  "Cut the intro. Keep the hook.",
  "You have 8 seconds before they bounce. Use them.",
  "Quantity is a strategy, not a compromise.",
  "Ten mediocre videos beat one unfinished masterpiece.",
  "Your taste grows faster than your skill. Ship anyway.",
  "Dopamine from TikTok costs you dopamine from shipping.",
  "One scroll becomes an hour. You know this.",
  "Put the phone in another room. Just do it.",
  "Boredom is the entrance fee to deep work.",
  "The 90-minute block is your best employee.",
  "Coffee works. Loops don't.",
  "Third coffee is a red flag, not a power-up.",
  "Water before caffeine. Always.",
  "Deep work is the only flex that compounds.",
  "Твои оправдания прозвучат убого в 30.",
  "Freedom comes to the stubborn, not the talented.",
  "The 9-to-5 isn't a job, it's a cage with AC.",
  "Build leverage while broke, not after.",
  "Sell hours once, then sell the same hour forever.",
  "Employee mode is a habit, not a condition.",
  "If your income stops when you stop, you own nothing.",
  "The best safety net is a second income stream.",
  "Work for yourself like your rent depends on it.",
  "Money buys time. Time buys everything else.",
  "Mortgage your weekends for five years. Own your life forever.",
  "You don't need $10k to start. You need to start.",
  "Хочешь свободу? Построй систему, которая работает без тебя.",
  "Every video is a lottery ticket you keep earning.",
  "The algorithm is patient. Be patient with it.",
  "Consistency is louder than creativity.",
  "Post on bad days especially. That's the system.",
  "100 videos. No excuses. No shortcuts.",
  "Your first viral video is hiding in video 47.",
  "Don't chase trends, chase formats you can repeat.",
  "Ship weekly. Ship weekly. Ship weekly.",
  "The pain of starting is always bigger than the task.",
  "Momentum is a skill you practice daily.",
  "Идеальный момент не придёт. Ты его создашь.",
  "Doubt is free. Action costs reps.",
  "Your brain will lie. Your calendar won't.",
  "If it's in your head, it doesn't exist yet.",
  "Write it down or watch it evaporate.",
  "Notes today, scripts tomorrow, money next quarter.",
  "The boring path is the only one that pays.",
  "Progress hides in the reps no one sees.",
  "Burnout comes from fake work, not real work.",
  "Real work ends. Fake work fills the day.",
  "Inbox zero is a lie. Output matters.",
  "Don't confuse movement with progress.",
  "Закрой TikTok. Открой камеру.",
  "Your future house is being built by today's boring reps.",
  "The market pays for finished, not perfect.",
  "Drop the precious. Keep the published.",
  "Your hero makes it look easy. It wasn't.",
  "Every expert you admire has a 'cringe' folder.",
  "Your cringe era is a receipt for growth.",
  "Post it and don't check stats for 48 hours.",
  "Analytics is a trap if it's your only dopamine.",
  "Check once a day. Then get back to work.",
  "Validation from mom isn't data. It's love.",
  "Stop reading comments for the first hour.",
  "Ты не ленивый. Ты в ловушке оптимизации.",
  "If you're researching the 5th tool, you're stalling.",
  "The tool you have is the best tool you have.",
  "CapCut is fine. Final Cut is fine. Pick one.",
  "You're not behind. You're just starting later, loudly.",
  "20 is young. 25 is young. 30 is young. Go.",
  "The clock only matters if you measure by excuses.",
  "Build the skill stack, not the excuse stack.",
  "Focus is a muscle. You've been skipping leg day.",
  "Train focus like you train biceps.",
  "Your attention is your paycheck. Spend it well.",
  "Notifications off. Forever. Yes, really.",
  "Каждое уведомление крадёт у тебя минуту и идею.",
  "The person who wins owns their calendar.",
  "Don't plan the year. Plan the week.",
  "Sunday night beats Monday morning.",
  "Review last week before you plan next week.",
  "Retrospective is a tool, not a confession.",
  "Missed a day? Skip the guilt, hit the next.",
  "Two misses is a pattern. Three is a lifestyle.",
  "Never skip twice. That's the whole rule.",
  "The streak matters less than the return.",
  "Быстро упал, быстро встал. Всё.",
  "Comparison to yesterday's you is the only fair fight.",
  "Your 12-year-old self would be proud. Keep going.",
  "Your 40-year-old self is begging you to start.",
  "Consistency beats intensity every quarter.",
  "You don't need a breakthrough. You need a Tuesday.",
  "Tuesday reps. Wednesday reps. That's the brand.",
  "The content creator who shows up wins.",
  "You can't out-edit bad ideas. Test more ideas.",
  "Ideas are cheap. Published ideas are not.",
  "Your notes app is not a body of work.",
  "Translate ideas into uploads within 72 hours.",
  "Идея в голове не кормит. Идея в релизе кормит.",
  "Sell before you're ready. Ready is a lie.",
  "Confidence arrives after the reps, never before.",
  "Waiting to feel ready is the richest procrastination.",
  "Delete the reference folder. Make the thing.",
  "Inspiration expires. Use it within 24 hours.",
  "The 'perfect setup' is a myth you keep buying.",
  "You don't need new gear. You need new footage.",
  "Good enough and shipped beats excellent and hidden.",
  "If nobody watches, it's practice. Practice is the job.",
  "Zero views today is data, not judgment.",
  "Нет просмотров? Значит тренируешься бесплатно. Хорошо.",
  "Do the work nobody sees for 18 months.",
  "After that, they can't unsee you.",
  "Luck is volume plus patience.",
  "Your next video is not the big one. The one after is.",
  "Keep a 'cringe folder' and never open it.",
  "Don't romanticize the struggle. Just finish it.",
  "The grind isn't sexy. That's why it works.",
  "Hard things stay hard. You get stronger.",
  "Build calluses in private, perform in public.",
  "Closed mouths don't get fed, neither do unpublished channels.",
  "Ten bad titles before one good title. Always.",
  "Write 20 titles. Pick the worst. Rewrite it.",
  "Your best hook is probably line 14 of the draft.",
  "Cut everything before the second sentence.",
  "Hooks aren't clever, they're specific.",
  "Specificity sells. Abstraction dies.",
  "Абстракция скучная. Детали залипают.",
  "Name the dollar amount. Name the time. Name the person.",
  "Don't say 'lots'. Say '47'.",
  "You're one boring video away from unsubscribes.",
  "Entertain first. Teach second. Sell third.",
  "If you're not bored of your own message, you haven't said it enough.",
  "Repetition isn't lazy. It's marketing.",
  "Say the same thing 50 different ways.",
  "Your audience isn't memorizing you, they're glimpsing you.",
  "Remind them every video who you are.",
  "Brand is what you repeat. Simple as that.",
  "Pick a lane for 12 months. Drive fast.",
  "Lane-hopping is how small channels stay small.",
  "Выбери одну тему и убей её.",
  "Niche is not a prison, it's a runway.",
  "Broaden only after you've owned a pocket.",
  "Depth first. Breadth later. Maybe never.",
  "You can be famous in a small room.",
  "A thousand true fans beats a million impressions.",
  "One superfan today. One hundred by year end.",
  "Replies in DMs build empires quieter than posts.",
  "Talk to your first subscriber like a co-founder.",
  "The first 1,000 subs are handmade. Earn them.",
  "Первая тысяча самая ценная. Работай вручную.",
  "Fame is a side effect. Freedom is the goal.",
  "Don't date the platform. Build the asset.",
  "Email list. Newsletter. Own something they can't take.",
  "YouTube can die tomorrow. Your skills can't.",
  "The skill is the asset. The channel is the delivery.",
  "Stack skills like Legos. Ship the tower.",
  "Editing, writing, speaking, selling. Pick two this quarter.",
  "Multi-skill beats single talent in the long run.",
  "Generalist with deep spikes wins the decade.",
  "Bore yourself learning the fundamentals.",
  "Скучные основы кормят годами.",
  "You're not a brand yet. You're a rep counter.",
  "Count the reps. Don't count the followers.",
  "Followers are a lagging indicator of reps.",
  "Reps compound silently until they don't.",
  "You can't feel compounding. That's why it works.",
  "Trust the math. The math is patient.",
  "One percent better is ridiculous and real.",
  "1.01 to the 365th is 37.8. Look it up.",
  "Your worst month is still a month of reps.",
  "Even a sick week still has two uploads.",
  "Плохая неделя это не ноль. Если есть хотя бы один релиз.",
  "Don't wait to feel like it. You won't.",
  "The mood comes from the action, not before it.",
  "Move first. Feelings follow.",
  "Lace up. Start recording. The rest is easy.",
  "Recording is 80% of the fight.",
  "Once it's recorded, it will be published.",
  "The hard part is always 'open the camera'.",
  "Open the camera. Everything else is downhill.",
  "Stop rewriting. Start recording.",
  "Перестань переписывать. Начни снимать.",
  "Your best ideas happen after the 10th minute of recording.",
  "Record 30 minutes. Keep 3.",
  "Cutting is where your voice gets sharp.",
  "Edit like you hate your own voice. Then publish.",
  "Soft edits make soft videos.",
  "Cut the breath. Cut the 'um'. Cut the warmup.",
  "Every second earns its place or gets deleted.",
  "Rewatch at 1.5x. Cut whatever sounds slow.",
  "Pacing is king. Personality is queen.",
  "Монотонный голос убивает хороший скрипт.",
  "Vary the cadence. Slow, fast, pause, punch.",
  "Silence is a tool. Use it on purpose.",
  "Music under voice. Never over.",
  "B-roll is a patch, not a personality.",
  "Your face holds more than your cutaways.",
  "Look at the lens. Not the screen. The lens.",
  "Eye contact wins retention. Boring but true.",
  "The first 3 seconds is the entire job.",
  "Hook. Promise. Deliver. Repeat.",
  "Don't overpromise. Overdeliver the frame.",
  "Клиффхэнгер в каждом углу видео.",
  "Tease the next beat. Don't let them rest.",
  "Rest is for the outro. Which should be short.",
  "End with a reason to click the next one.",
  "Playlists are compounding machines. Build them.",
  "One channel. Five playlists. Ten years.",
  "Think in series, not episodes.",
  "Series beat standalone 9 times out of 10.",
  "Your format is your factory.",
  "Nail one format, print 50 copies.",
  "Перестань изобретать. Начни копировать свою же формулу.",
  "Don't reinvent weekly. Repeat what works.",
  "Originality is a side effect of volume.",
  "You can't manufacture 'authentic'. You reveal it.",
  "Authentic = tired and still shipping.",
  "Tired is not a reason to skip. It's a reason to simplify.",
  "Simplify the day. Don't skip it.",
  "Low-energy day = low-energy deliverable, but still a deliverable.",
  "Half-rep counts. Zero-rep doesn't.",
  "Show up at 30% rather than 0%.",
  "Плохая тренировка лучше пропущенной. Всегда.",
  "Morning sun. Morning water. Morning movement.",
  "Your nervous system runs the whole show.",
  "Regulate the body, the brain follows.",
  "Cold shower at the start, warm shower at the end.",
  "Breath work is free Xanax. Use it.",
  "Four-seven-eight breathing before any hard task.",
  "Caffeine is a tool, not a personality.",
  "Cut caffeine by 2pm. Sleep will thank you.",
  "Blue light at midnight steals Monday's energy.",
  "Экран после 11 вечера это кража у утра.",
  "Protect the first 90 minutes. Everything else is negotiable.",
  "Mornings are for making. Afternoons are for fixing.",
  "Evenings are for resetting. Not for launching.",
  "Never launch anything after 7pm.",
  "Never make big decisions when tired or hungry.",
  "HALT: hungry, angry, lonely, tired. Check yourself.",
  "The version of you at 3am is not a reliable narrator.",
  "Wait 24 hours before quitting anything.",
  "Wait 24 hours before posting anything angry.",
  "Подожди сутки. Тогда решай.",
  "Money isn't the scoreboard. Freedom is.",
  "Measure months by uploads, not by dollars.",
  "Dollars are a trailing indicator of skill.",
  "First make it consistent. Then make it big.",
  "Small, weekly, forever.",
  "Forever is the part most people skip.",
  "Everyone quits right before the curve bends.",
  "The curve bends in year two, not week four.",
  "Plant trees, don't pick fruit.",
  "Сажай деревья. Фрукты позже.",
  "Stop checking if the seed is growing. Water it.",
  "The answer is always: more reps, less opinions.",
  "Unfollow anyone who makes you feel behind.",
  "Your feed is your mindset. Curate hard.",
  "Feed rule: 80% people shipping. 20% inspiration. 0% noise.",
  "If it doesn't make you work or rest, unfollow.",
  "Social media is a tool. You're the operator.",
  "Post more than you consume. Always.",
  "Creator-to-consumer ratio is your real health metric.",
  "Producer mode is a daily choice, not a mood.",
  "Ты либо создаёшь, либо потребляешь. Выбирай чаще первое.",
  "Being 'too busy' to train is a lie with a deadline.",
  "Health is not optional. It's the stack.",
  "Sick you earns nothing. Healthy you scales.",
  "Sleep 8. Not 7. Not 'whenever'. 8.",
  "Steps beat cardio for a creator's sanity.",
  "Walk an hour after lunch. Ideas will come.",
  "The best scripts are written on walks.",
  "Phone-less walks are the new meditation.",
  "Silence is a creative resource. Stock up.",
  "Молчание это инструмент, не пауза.",
  "Protein at breakfast. Don't argue.",
  "Sugar crashes your entire afternoon. Every time.",
  "Lunch shouldn't need a nap afterwards.",
  "Alcohol steals three days, not one night.",
  "Your brain on hangover is not your brain.",
  "The bipolar discount on booze is 10x, not 1x.",
  "Sleep, sun, food, lift. Boring saves lives.",
  "The routine isn't optional. It's the medication.",
  "Stability is the new flex.",
  "Стабильность это новый понт.",
  "You don't need to feel amazing. You need to feel steady.",
  "Steady wins. Amazing burns out.",
  "Don't chase peaks. Raise the floor.",
  "Raise the floor, and peaks happen naturally.",
  "Your worst week should still be functional.",
  "Build a floor you're not ashamed of.",
  "The baseline is what you ship on your worst day.",
  "A baseline of one video a week is already a career.",
  "One post a week for five years is a body of work.",
  "52 x 5 = 260 swings at the plate. Someone hits.",
  "260 попыток за 5 лет. Кто-то из них зайдёт.",
  "Stop rehearsing the pitch. Make the pitch.",
  "Done is a feature. Ship it."
];
