// One quote per day-of-year, rotated deterministically by dayOfYear() % length.
// English only. Heavy on ancient philosophy (Stoics, Greeks, Eastern), with
// substantive modern thinkers as well. No creator-hustle slogans.
export const QUOTES_365 = [
  // ═══ MARCUS AURELIUS — Meditations ═══
  "You have power over your mind — not outside events. Realize this, and you will find strength. — Marcus Aurelius",
  "Waste no more time arguing what a good man should be. Be one. — Marcus Aurelius",
  "The happiness of your life depends upon the quality of your thoughts. — Marcus Aurelius",
  "If it is not right, do not do it; if it is not true, do not say it. — Marcus Aurelius",
  "Confine yourself to the present. — Marcus Aurelius",
  "The impediment to action advances action. What stands in the way becomes the way. — Marcus Aurelius",
  "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love. — Marcus Aurelius",
  "Reject your sense of injury and the injury itself disappears. — Marcus Aurelius",
  "He who lives in harmony with himself lives in harmony with the universe. — Marcus Aurelius",
  "Begin each day by telling yourself: today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness. — Marcus Aurelius",
  "It is not death that a man should fear, but he should fear never beginning to live. — Marcus Aurelius",
  "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look. — Marcus Aurelius",
  "Dwell on the beauty of life. Watch the stars, and see yourself running with them. — Marcus Aurelius",
  "If you are distressed by anything external, the pain is not due to the thing itself but to your estimate of it. — Marcus Aurelius",
  "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth. — Marcus Aurelius",
  "Loss is nothing else but change, and change is Nature's delight. — Marcus Aurelius",
  "How much time he gains who does not look to see what his neighbor says or does. — Marcus Aurelius",
  "The best revenge is to be unlike him who performed the injury. — Marcus Aurelius",
  "Accept the things to which fate binds you, and love the people with whom fate brings you together. — Marcus Aurelius",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. — Marcus Aurelius",

  // ═══ EPICTETUS — Discourses & Enchiridion ═══
  "It is not what happens to you, but how you react to it that matters. — Epictetus",
  "Wealth consists not in having great possessions, but in having few wants. — Epictetus",
  "First say to yourself what you would be; and then do what you have to do. — Epictetus",
  "No man is free who is not master of himself. — Epictetus",
  "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. — Epictetus",
  "Don't explain your philosophy. Embody it. — Epictetus",
  "We have two ears and one mouth so that we can listen twice as much as we speak. — Epictetus",
  "If you wish to improve, be content to be thought foolish and stupid. — Epictetus",
  "Only the educated are free. — Epictetus",
  "Make the best use of what is in your power, and take the rest as it happens. — Epictetus",
  "Difficulties show a person's character. — Epictetus",
  "Circumstances don't make the man, they only reveal him to himself. — Epictetus",
  "First learn the meaning of what you say, and then speak. — Epictetus",
  "Other people's views and troubles can be contagious. Don't sabotage yourself by unwittingly adopting negative, unproductive attitudes through your associations with others. — Epictetus",
  "Caretake this moment. Immerse yourself in its particulars. Respond to this person, this challenge, this deed. — Epictetus",

  // ═══ SENECA — Letters from a Stoic ═══
  "While we are postponing, life speeds by. — Seneca",
  "It is not that we have a short time to live, but that we waste a lot of it. — Seneca",
  "Luck is what happens when preparation meets opportunity. — Seneca",
  "He who is brave is free. — Seneca",
  "We suffer more often in imagination than in reality. — Seneca",
  "True happiness is to enjoy the present, without anxious dependence upon the future. — Seneca",
  "Difficulties strengthen the mind, as labor does the body. — Seneca",
  "Sometimes even to live is an act of courage. — Seneca",
  "If a man knows not to which port he sails, no wind is favorable. — Seneca",
  "Begin at once to live, and count each separate day as a separate life. — Seneca",
  "As is a tale, so is life: not how long it is, but how good it is, is what matters. — Seneca",
  "Most powerful is he who has himself in his own power. — Seneca",
  "Hang on to your youthful enthusiasms — you'll be able to use them better when you're older. — Seneca",
  "It does not matter how many books you have, but how good are the books which you have. — Seneca",
  "Time discovers truth. — Seneca",
  "He who fears death will never do anything worthy of a living man. — Seneca",
  "We are more often frightened than hurt; and we suffer more in apprehension than from reality. — Seneca",
  "Curiosity is a kind of unprofitable elegance, but profitable diligence belongs to the soul. — Seneca",
  "No man was ever wise by chance. — Seneca",

  // ═══ HERACLITUS ═══
  "No man ever steps in the same river twice, for it's not the same river and he's not the same man. — Heraclitus",
  "Character is destiny. — Heraclitus",
  "The only constant in life is change. — Heraclitus",
  "Big results require big ambitions. — Heraclitus",
  "Much learning does not teach understanding. — Heraclitus",
  "The soul is dyed the color of its thoughts. — Heraclitus",
  "Eyes are more accurate witnesses than ears. — Heraclitus",
  "The road up and the road down are the same thing. — Heraclitus",
  "Day by day, what you choose, what you think and what you do is who you become. — Heraclitus",

  // ═══ SOCRATES ═══
  "The unexamined life is not worth living. — Socrates",
  "I know that I am intelligent, because I know that I know nothing. — Socrates",
  "An honest man is always a child. — Socrates",
  "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less. — Socrates",
  "Be slow to fall into friendship; but when thou art in, continue firm and constant. — Socrates",
  "Beware the barrenness of a busy life. — Socrates",
  "He is richest who is content with the least, for content is the wealth of nature. — Socrates",
  "Strong minds discuss ideas, average minds discuss events, weak minds discuss people. — Socrates",
  "The greatest way to live with honor in this world is to be what we pretend to be. — Socrates",
  "Education is the kindling of a flame, not the filling of a vessel. — Socrates",

  // ═══ PLATO ═══
  "Wise men speak because they have something to say; fools because they have to say something. — Plato",
  "The first and greatest victory is to conquer yourself. — Plato",
  "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. — Plato",
  "Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination. — Plato",
  "The measure of a man is what he does with power. — Plato",
  "Necessity is the mother of invention. — Plato",
  "Be kind, for everyone you meet is fighting a harder battle. — Plato",
  "The beginning is the most important part of the work. — Plato",
  "The worst form of injustice is pretended justice. — Plato",
  "Ignorance, the root and stem of all evil. — Plato",

  // ═══ ARISTOTLE ═══
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
  "It is during our darkest moments that we must focus to see the light. — Aristotle",
  "Knowing yourself is the beginning of all wisdom. — Aristotle",
  "Patience is bitter, but its fruit is sweet. — Aristotle",
  "Pleasure in the job puts perfection in the work. — Aristotle",
  "Happiness depends upon ourselves. — Aristotle",
  "The whole is greater than the sum of its parts. — Aristotle",
  "What is a friend? A single soul dwelling in two bodies. — Aristotle",
  "He who has overcome his fears will truly be free. — Aristotle",
  "Educating the mind without educating the heart is no education at all. — Aristotle",
  "The roots of education are bitter, but the fruit is sweet. — Aristotle",
  "Learning is not child's play; we cannot learn without pain. — Aristotle",

  // ═══ DIOGENES & CYNICS ═══
  "I am not an Athenian or a Greek, but a citizen of the world. — Diogenes",
  "He has the most who is most content with the least. — Diogenes",
  "It is not that I am mad, it is only that my head is different from yours. — Diogenes",
  "The foundation of every state is the education of its youth. — Diogenes",
  "Dogs and philosophers do the greatest good and get the fewest rewards. — Diogenes",

  // ═══ EPICURUS ═══
  "Do not spoil what you have by desiring what you have not. — Epicurus",
  "He who is not satisfied with a little, is satisfied with nothing. — Epicurus",
  "Not what we have but what we enjoy, constitutes our abundance. — Epicurus",
  "The greater the difficulty, the more glory in surmounting it. — Epicurus",
  "Death does not concern us, because as long as we exist, death is not here. — Epicurus",
  "Misfortune seldom intrudes upon the wise man; his greatest and highest interests are directed by reason throughout the course of life. — Epicurus",

  // ═══ LAO TZU & TAO TE CHING ═══
  "The journey of a thousand miles begins with a single step. — Lao Tzu",
  "Knowing others is intelligence; knowing yourself is true wisdom. — Lao Tzu",
  "When I let go of what I am, I become what I might be. — Lao Tzu",
  "Care about what other people think and you will always be their prisoner. — Lao Tzu",
  "Mastering others is strength. Mastering yourself is true power. — Lao Tzu",
  "He who knows that enough is enough will always have enough. — Lao Tzu",
  "Silence is a source of great strength. — Lao Tzu",
  "Nature does not hurry, yet everything is accomplished. — Lao Tzu",
  "Music in the soul can be heard by the universe. — Lao Tzu",
  "Time is a created thing. To say 'I don't have time,' is to say, 'I don't want to.' — Lao Tzu",
  "Anticipate the difficult by managing the easy. — Lao Tzu",
  "Watch your thoughts, they become your words; watch your words, they become your actions. — Lao Tzu",

  // ═══ CONFUCIUS ═══
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "The man who moves a mountain begins by carrying away small stones. — Confucius",
  "Real knowledge is to know the extent of one's ignorance. — Confucius",
  "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps. — Confucius",
  "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
  "Choose a job you love, and you will never have to work a day in your life. — Confucius",
  "He who learns but does not think, is lost! He who thinks but does not learn is in great danger. — Confucius",
  "Everything has beauty, but not everyone sees it. — Confucius",
  "To know what you know and what you do not know, that is true knowledge. — Confucius",
  "By three methods we may learn wisdom: first, by reflection, which is noblest; second, by imitation, which is easiest; third, by experience, which is the bitterest. — Confucius",

  // ═══ SUN TZU — Art of War ═══
  "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win. — Sun Tzu",
  "In the midst of chaos, there is also opportunity. — Sun Tzu",
  "The supreme art of war is to subdue the enemy without fighting. — Sun Tzu",
  "Know thyself, know thy enemy. A thousand battles, a thousand victories. — Sun Tzu",
  "Opportunities multiply as they are seized. — Sun Tzu",
  "The greatest victory is that which requires no battle. — Sun Tzu",
  "If you know the enemy and know yourself, you need not fear the result of a hundred battles. — Sun Tzu",
  "Quickness is the essence of war. — Sun Tzu",

  // ═══ BUDDHA & EASTERN ═══
  "All that we are is the result of what we have thought. — Buddha",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. — Buddha",
  "Pain is certain, suffering is optional. — Buddha",
  "Three things cannot be long hidden: the sun, the moon, and the truth. — Buddha",
  "The mind is everything. What you think, you become. — Buddha",
  "Better than a thousand hollow words, is one word that brings peace. — Buddha",
  "You yourself, as much as anybody in the entire universe, deserve your love and affection. — Buddha",
  "There is no path to happiness: happiness is the path. — Buddha",
  "It is better to travel well than to arrive. — Buddha",
  "Anger will never disappear so long as thoughts of resentment are cherished in the mind. — Buddha",

  // ═══ CICERO ═══
  "If you have a garden and a library, you have everything you need. — Cicero",
  "The life given us, by nature is short; but the memory of a well-spent life is eternal. — Cicero",
  "The function of wisdom is to discriminate between good and evil. — Cicero",
  "The higher we are placed, the more humbly we should walk. — Cicero",
  "The enemy is within the gates; it is with our own luxury, our own folly, our own criminality that we have to contend. — Cicero",
  "To be ignorant of what occurred before you were born is to remain always a child. — Cicero",
  "Friendship improves happiness and abates misery, by the doubling of our joy and the dividing of our grief. — Cicero",

  // ═══ NIETZSCHE ═══
  "He who has a why to live can bear almost any how. — Nietzsche",
  "That which does not kill us makes us stronger. — Nietzsche",
  "You must have chaos within you to give birth to a dancing star. — Nietzsche",
  "The man who cannot believe in himself cannot believe in anything else. — Nietzsche",
  "The snake which cannot cast its skin has to die. — Nietzsche",
  "Without music, life would be a mistake. — Nietzsche",
  "He who fights with monsters should be careful lest he thereby become a monster. — Nietzsche",
  "There are no facts, only interpretations. — Nietzsche",
  "When you stare into the abyss, the abyss stares back into you. — Nietzsche",
  "The individual has always had to struggle to keep from being overwhelmed by the tribe. — Nietzsche",
  "In heaven, all the interesting people are missing. — Nietzsche",
  "Every deep thinker is more afraid of being understood than of being misunderstood. — Nietzsche",

  // ═══ EMERSON ═══
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Emerson",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Emerson",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. — Emerson",
  "The only person you are destined to become is the person you decide to be. — Emerson",
  "Once you make a decision, the universe conspires to make it happen. — Emerson",
  "What you do speaks so loudly that I cannot hear what you say. — Emerson",
  "Self-trust is the first secret of success. — Emerson",
  "Whatever you do, you need courage. — Emerson",
  "A man is what he thinks about all day long. — Emerson",
  "The mind, once stretched by a new idea, never returns to its original dimensions. — Emerson",

  // ═══ THOREAU ═══
  "Most men lead lives of quiet desperation. — Thoreau",
  "Go confidently in the direction of your dreams. Live the life you have imagined. — Thoreau",
  "Our life is frittered away by detail. Simplify, simplify, simplify. — Thoreau",
  "It's not what you look at that matters, it's what you see. — Thoreau",
  "Things do not change; we change. — Thoreau",
  "However mean your life is, meet it and live it. — Thoreau",
  "Rather than love, than money, than fame, give me truth. — Thoreau",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. — Thoreau",

  // ═══ CAMUS / EXISTENTIALISTS ═══
  "In the depth of winter, I finally learned that within me there lay an invincible summer. — Camus",
  "The only way to deal with this life meaningfully is to find one's passion and put everything into it. — Camus",
  "We must imagine Sisyphus happy. — Camus",
  "Real generosity towards the future lies in giving all to the present. — Camus",
  "Life is a sum of all your choices. — Camus",
  "Don't walk in front of me, I may not follow. Don't walk behind me, I may not lead. Walk beside me and be my friend. — Camus",
  "Every act of rebellion expresses a nostalgia for innocence. — Camus",

  // ═══ KIERKEGAARD ═══
  "Anxiety is the dizziness of freedom. — Kierkegaard",
  "Life can only be understood backwards; but it must be lived forwards. — Kierkegaard",
  "To dare is to lose one's footing momentarily. Not to dare is to lose oneself. — Kierkegaard",
  "Don't forget to love yourself. — Kierkegaard",
  "Patience is necessary, and one cannot reap immediately where one has sown. — Kierkegaard",

  // ═══ MONTAIGNE ═══
  "The greatest thing in the world is to know how to belong to oneself. — Montaigne",
  "He who fears he shall suffer, already suffers what he fears. — Montaigne",
  "My life has been filled with terrible misfortune; most of which never happened. — Montaigne",
  "I do not speak the minds of others except to speak my own mind better. — Montaigne",
  "There is no conversation more boring than the one where everybody agrees. — Montaigne",

  // ═══ PASCAL ═══
  "All of humanity's problems stem from man's inability to sit quietly in a room alone. — Pascal",
  "The heart has its reasons of which reason knows nothing. — Pascal",
  "I have made this letter longer than usual, only because I have not had the time to make it shorter. — Pascal",
  "Small minds are concerned with the extraordinary, great minds with the ordinary. — Pascal",
  "Man is equally incapable of seeing the nothingness from which he emerges and the infinity in which he is engulfed. — Pascal",

  // ═══ SCHOPENHAUER ═══
  "Talent hits a target no one else can hit; genius hits a target no one else can see. — Schopenhauer",
  "It is the courage to make a clean breast of it in face of every question that makes the philosopher. — Schopenhauer",
  "The two enemies of human happiness are pain and boredom. — Schopenhauer",
  "Compassion is the basis of morality. — Schopenhauer",
  "A man can be himself only so long as he is alone. — Schopenhauer",

  // ═══ DOSTOEVSKY ═══
  "The mystery of human existence lies not in just staying alive, but in finding something to live for. — Dostoevsky",
  "Above all, don't lie to yourself. The man who lies to himself can never see the truth. — Dostoevsky",
  "Pain and suffering are always inevitable for a large intelligence and a deep heart. — Dostoevsky",
  "A real gentleman, even if he loses everything he owns, must show no emotion. — Dostoevsky",
  "Taking a new step, uttering a new word, is what people fear most. — Dostoevsky",
  "If you want to be respected by others, the great thing is to respect yourself. — Dostoevsky",

  // ═══ TOLSTOY ═══
  "Everyone thinks of changing the world, but no one thinks of changing himself. — Tolstoy",
  "The two most powerful warriors are patience and time. — Tolstoy",
  "Boredom: the desire for desires. — Tolstoy",
  "Happy is he who is happy in his family. — Tolstoy",
  "All happy families are alike; each unhappy family is unhappy in its own way. — Tolstoy",

  // ═══ JUNG ═══
  "I am not what happened to me, I am what I choose to become. — Carl Jung",
  "Until you make the unconscious conscious, it will direct your life and you will call it fate. — Carl Jung",
  "The privilege of a lifetime is to become who you truly are. — Carl Jung",
  "Knowing your own darkness is the best method for dealing with the darknesses of other people. — Carl Jung",
  "Everything that irritates us about others can lead us to an understanding of ourselves. — Carl Jung",
  "Where your fear is, there is your task. — Carl Jung",

  // ═══ VIKTOR FRANKL ═══
  "Between stimulus and response there is a space. In that space is our power to choose our response. — Viktor Frankl",
  "Those who have a 'why' to live, can bear with almost any 'how'. — Viktor Frankl",
  "When we are no longer able to change a situation, we are challenged to change ourselves. — Viktor Frankl",
  "Everything can be taken from a man but one thing: the last of human freedoms — to choose one's attitude in any given set of circumstances. — Viktor Frankl",
  "Life is never made unbearable by circumstances, but only by lack of meaning and purpose. — Viktor Frankl",

  // ═══ NAVAL RAVIKANT ═══
  "The most important skill for getting rich is becoming a perpetual learner. — Naval Ravikant",
  "Learn to sell. Learn to build. If you can do both, you will be unstoppable. — Naval Ravikant",
  "All the real benefits in life come from compound interest. — Naval Ravikant",
  "Specific knowledge is found by pursuing your genuine curiosity, not by following whatever is hot right now. — Naval Ravikant",
  "Read what you love until you love to read. — Naval Ravikant",
  "Desire is a contract you make with yourself to be unhappy until you get what you want. — Naval Ravikant",
  "A calm mind, a fit body, and a house full of love. These things cannot be bought — they must be earned. — Naval Ravikant",
  "Easy choices, hard life. Hard choices, easy life. — Naval Ravikant",
  "If you cannot decide, the answer is no. — Naval Ravikant",
  "Play long-term games with long-term people. — Naval Ravikant",

  // ═══ NASSIM TALEB ═══
  "The three most harmful addictions are heroin, carbohydrates, and a monthly salary. — Nassim Taleb",
  "Robust is when you care more about the few who like your work than the multitude who hates it. — Nassim Taleb",
  "If you see fraud and do not say fraud, you are a fraud. — Nassim Taleb",
  "The opposite of success isn't failure, it is name-dropping. — Nassim Taleb",
  "The best way to verify that you are alive is by checking if you like variations. — Nassim Taleb",
  "Difficulty is the mother of invention. — Nassim Taleb",
  "An idea starts to be interesting when you get scared of taking it to its logical conclusion. — Nassim Taleb",

  // ═══ MISC DEEP THINKERS ═══
  "The cave you fear to enter holds the treasure you seek. — Joseph Campbell",
  "Follow your bliss and the universe will open doors where there were only walls. — Joseph Campbell",
  "We must let go of the life we have planned, so as to accept the one that is waiting for us. — Joseph Campbell",
  "Do the thing and you shall have the power. — Joseph Campbell",
  "What you can control is your work. What you cannot control is the recognition. — Anonymous",
  "The man who chases two rabbits catches neither. — Confucius",
  "Comparison is the thief of joy. — Theodore Roosevelt",
  "Whether you think you can or you think you can't, you're right. — Henry Ford",
  "The chief enemy of creativity is good sense. — Picasso",
  "I have not failed. I've just found 10,000 ways that won't work. — Edison",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Stay hungry, stay foolish. — Steve Jobs",
  "Your time is limited, don't waste it living someone else's life. — Steve Jobs",
  "Innovation distinguishes between a leader and a follower. — Steve Jobs",
  "The two most important days in your life are the day you are born and the day you find out why. — Mark Twain",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. — Mark Twain",
  "Whenever you find yourself on the side of the majority, it is time to pause and reflect. — Mark Twain",
  "Worrying is like paying a debt you don't owe. — Mark Twain",
  "Continuous improvement is better than delayed perfection. — Mark Twain",
  "The world breaks everyone, and afterward, some are strong at the broken places. — Hemingway",
  "There is no friend as loyal as a book. — Hemingway",
  "It is good to have an end to journey toward; but it is the journey that matters, in the end. — Ursula K. Le Guin",
  "If you are afraid of being lonely, don't try to be right. — Jules Renard",
  "The expert in anything was once a beginner. — Helen Hayes",
  "The only journey is the one within. — Rilke",
  "Be patient toward all that is unsolved in your heart and try to love the questions themselves. — Rilke",
  "The future enters into us, in order to transform itself in us, long before it happens. — Rilke",
  "Reading is to the mind what exercise is to the body. — Joseph Addison",
  "If we wait until we're ready, we'll be waiting for the rest of our lives. — Lemony Snicket",
  "Try not to become a man of success, but rather try to become a man of value. — Einstein",
  "Strive not to be a success, but rather to be of value. — Einstein",
  "Imagination is more important than knowledge. — Einstein",
  "In the middle of difficulty lies opportunity. — Einstein",
  "Anyone who has never made a mistake has never tried anything new. — Einstein",
  "The important thing is not to stop questioning. Curiosity has its own reason for existing. — Einstein",

  // ═══ MORE STOIC + ANCIENT ═══
  "Where there is no struggle, there is no strength. — Oprah Winfrey",
  "He who would learn to fly one day must first learn to stand and walk and run and climb and dance. — Nietzsche",
  "Out of difficulties grow miracles. — Jean de la Bruyère",
  "Patience is the companion of wisdom. — Saint Augustine",
  "The greatest weapon against stress is our ability to choose one thought over another. — William James",
  "We are what we believe we are. — C.S. Lewis",
  "The first step toward change is awareness. The second step is acceptance. — Nathaniel Branden",
  "Whatever you are, be a good one. — Lincoln",
  "If you want to lift yourself up, lift up someone else. — Booker T. Washington",
  "I have learned that to be with those I like is enough. — Walt Whitman",
  "Re-examine all that you have been told. Dismiss what insults your soul. — Walt Whitman",
  "Be curious, not judgmental. — Walt Whitman",
  "Life is what happens when you're busy making other plans. — John Lennon",
  "The trouble is, you think you have time. — Buddha (attrib.)",
  "We don't see things as they are, we see them as we are. — Anaïs Nin",
  "And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom. — Anaïs Nin",
  "Action expresses priorities. — Gandhi",
  "Be the change you wish to see in the world. — Gandhi",
  "An eye for an eye only ends up making the whole world blind. — Gandhi",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. — Gandhi",
  "The future depends on what you do today. — Gandhi",
  "Strength does not come from physical capacity. It comes from an indomitable will. — Gandhi",
  "First they ignore you, then they laugh at you, then they fight you, then you win. — Gandhi",

  // ═══ JAPANESE / ZEN ═══
  "Fall seven times, stand up eight. — Japanese proverb",
  "The bamboo that bends is stronger than the oak that resists. — Japanese proverb",
  "If you want to know the road ahead, ask those coming back. — Chinese proverb",
  "A journey of a thousand miles begins beneath one's feet. — Lao Tzu",
  "Smile, breathe and go slowly. — Thich Nhat Hanh",
  "The present moment is the only moment available to us, and it is the door to all moments. — Thich Nhat Hanh",
  "Walk as if you are kissing the Earth with your feet. — Thich Nhat Hanh",
  "Letting go gives us freedom, and freedom is the only condition for happiness. — Thich Nhat Hanh",
  "Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves. — Thich Nhat Hanh",
  "Wisdom tells me I am nothing. Love tells me I am everything. Between the two my life flows. — Nisargadatta Maharaj",
  "The pine teaches silence, the rock teaches stillness, and the lake teaches calmness. — Zen saying",
  "Wherever you are, be there totally. — Eckhart Tolle",
  "Acceptance looks like a passive state, but in reality it brings something entirely new into this world. — Eckhart Tolle",
  "The primary cause of unhappiness is never the situation but your thoughts about it. — Eckhart Tolle",
  "Life will give you whatever experience is most helpful for the evolution of your consciousness. — Eckhart Tolle",
  "If a tree is to grow tall, it must first sink deep roots. — Zen proverb",
  "The obstacle is the path. — Zen proverb",
  "Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water. — Zen proverb",
  "Sitting quietly, doing nothing, spring comes, and the grass grows by itself. — Zen proverb",
  "When the student is ready, the teacher will appear. — Buddhist proverb",

  // ═══ WORK / MASTERY (substantive, not hustle) ═══
  "The master has failed more times than the beginner has even tried. — Stephen McCranie",
  "Do what you love, love what you do, and deliver more than you promise. — Harvey Mackay",
  "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
  "Don't wish it were easier. Wish you were better. — Jim Rohn",
  "Take care of your body. It's the only place you have to live. — Jim Rohn",
  "Either you run the day or the day runs you. — Jim Rohn",
  "Your level of success will rarely exceed your level of personal development. — Jim Rohn",
  "You cannot change your destination overnight, but you can change your direction overnight. — Jim Rohn",
  "We must all suffer one of two things: the pain of discipline or the pain of regret. — Jim Rohn",
  "Success is nothing more than a few simple disciplines, practiced every day. — Jim Rohn",
  "Don't count the days, make the days count. — Muhammad Ali",
  "He who is not courageous enough to take risks will accomplish nothing in life. — Muhammad Ali",
  "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.' — Muhammad Ali",
  "Champions aren't made in gyms. They're made from something deep inside them — a desire, a dream, a vision. — Muhammad Ali",
  "It isn't the mountains ahead to climb that wear you out; it's the pebble in your shoe. — Muhammad Ali",
  "If you don't find time for exercise, you'll have to find time for illness. — Edward Stanley",
  "The body achieves what the mind believes. — Anonymous",
  "Discipline equals freedom. — Jocko Willink",
  "Good. — Jocko Willink",
  "Discipline starts every time you set the alarm. — Jocko Willink",
  "Don't expect to be motivated every day to get out there. Some days the hardest thing to do is to put your shoes on. — Jocko Willink",

  // ═══ SOLITUDE & QUIET ═══
  "Solitude is where I place my chaos to rest. — Nikki Rowe",
  "Loneliness is not the absence of company, it is the absence of self. — Anonymous",
  "The greatest thing in the world is to know how to belong to oneself. — Montaigne",
  "I never found a companion that was so companionable as solitude. — Thoreau",
  "I restore myself when I'm alone. — Marilyn Monroe",
  "Be alone — that is the secret of invention; be alone, that is when ideas are born. — Tesla",

  // ═══ TIME ═══
  "Lost time is never found again. — Benjamin Franklin",
  "It's not the load that breaks you down, it's the way you carry it. — Lou Holtz",
  "Yesterday is history, tomorrow is a mystery, today is a gift, that's why we call it 'the present'. — Master Oogway / Bil Keane",
  "The trouble with you is the trouble with us all. We have too much yesterday and too much tomorrow, and not enough today. — Anonymous",
  "Time you enjoy wasting is not wasted time. — Marthe Troly-Curtin",
  "An inch of time is an inch of gold but you can't buy that inch of time with an inch of gold. — Chinese proverb",
  "Better three hours too soon than a minute too late. — Shakespeare",

  // ═══ FAILURE & RESILIENCE ═══
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. — Edison",
  "It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all. — J.K. Rowling",
  "Rock bottom became the solid foundation on which I rebuilt my life. — J.K. Rowling",
  "Success consists of going from failure to failure without loss of enthusiasm. — Churchill",
  "If you're going through hell, keep going. — Churchill",
  "Never never never give up. — Churchill",
  "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty. — Churchill",
  "Fall down seven times, get up eight. — Japanese proverb",
  "Do not judge me by my successes, judge me by how many times I fell down and got back up again. — Nelson Mandela",
  "It always seems impossible until it's done. — Nelson Mandela",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
];
